name = "ntnux"
compatibility_date = "2026-02-12"

[assets]
directory = ".output/public"
<<<<<<< HEAD
# binding = "ASSETS"
# run_worker_first = false
=======
binding = "ASSETS"
run_worker_first = false # è®“éœæ…‹æª”æ¡ˆå„ªå…ˆè¢«è®€å– (SPA æ¨¡å¼å»ºè­°)
>>>>>>> fd0dbd0... ðŸ’š æ–°å¢ž cloudflare éƒ¨ç½²è¨­å®šæª”

[observability]
enabled = true